# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 761, 411))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("fox.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.fox = QtWidgets.QPushButton(self.centralwidget)
        self.fox.setGeometry(QtCore.QRect(40, 460, 291, 61))
        self.fox.setObjectName("fox")
        self.bull = QtWidgets.QPushButton(self.centralwidget)
        self.bull.setGeometry(QtCore.QRect(360, 460, 261, 61))
        self.bull.setObjectName("bull")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.fox.clicked.connect(self.show_fox)
        self.bull.clicked.connect(self.show_bull)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fox.setText(_translate("MainWindow", "FOX"))
        self.bull.setText(_translate("MainWindow", "BULL"))

    def show_fox(self):
        self.label.setPixmap(QtGui.QPixmap("fox.jpg"))

    def show_bull(self):
        self.label.setPixmap(QtGui.QPixmap("bull.jpg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
